name: CI/CD Build

on:
  push:
    branches: [main]

concurrency: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Check out the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 💿 Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: 📥 Install dependencies
        run: npm install && npm run clean && npm run prepare

      - name: 🕵 Lint the code
        run: npm run lint

      - name: 🕵 Typecheck the code
        run: npm run typecheck

      - name: 💿 Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release